name: predomics

services:
  app:
    container_name: predomics-web
    build:
      context: ..
      dockerfile: predomicsapp-web/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - app-data:/app/data
    environment:
      - PREDOMICS_DATA_DIR=/app/data
      - PREDOMICS_UPLOAD_DIR=/app/data/uploads
      - PREDOMICS_PROJECT_DIR=/app/data/projects
      - PREDOMICS_SAMPLE_DIR=/app/data/qin2014_cirrhosis
    restart: unless-stopped

volumes:
  app-data:
