{{- if not .Values.secrets.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "predomicsapp.fullname" . }}
  labels:
    {{- include "predomicsapp.labels" . | nindent 4 }}
type: Opaque
data:
  secret-key: {{ .Values.secrets.secretKey | default (randAlphaNum 64) | b64enc | quote }}
  {{- if .Values.postgresql.enabled }}
  postgres-password: {{ .Values.secrets.postgresPassword | default (randAlphaNum 32) | b64enc | quote }}
  {{- end }}
{{- end }}
